/** @type {import('stylelint').Config} */
export default {
    extends: ["stylelint-config-standard-scss"],
    overrides: [
        {
            files: ["*.vue", "**/*.vue"],
            extends: ["stylelint-config-standard-scss", "stylelint-config-standard-vue/scss"]
        }
    ],
    ignoreFiles: ["resources/app/styles/vendor/**/*"],
    plugins: ["stylelint-scss", "stylelint-order"],
    rules: {
        "declaration-empty-line-before": null,
        "selector-class-pattern": "^[a-z]([-]?[a-z0-9]+)*(__[a-z0-9]([-]?[a-z0-9]+)*)?(--[a-z0-9]([-]?[a-z0-9]+)*)?$",
        "color-named": [
            "never",
            {
                ignore: ["inside-function"]
            }
        ],
        "font-family-name-quotes": "always-where-recommended",
        // "order/order": ["dollar-variables", "custom-properties", "declarations", "rules", "at-rules"],
        "order/properties-order": [
            {
                groupName: "display",
                emptyLineBefore: "always",
                unspecified: "ignore",
                emptyLineMinimumPropertyThreshold: 0,
                properties: [
                    "all",
                    "display",
                    "position",
                    "inset",
                    "inset-block-start",
                    "inset-block-end",
                    "inset-inline-start",
                    "inset-inline-end",
                    "inset-block",
                    "inset-inline",
                    "top",
                    "right",
                    "bottom",
                    "left",
                    "z-index",
                    "float",
                    "clear",
                    "align-items",
                    "align-content",
                    "align-self",
                    "justify-content",
                    "flex-direction",
                    "flex-grow",
                    "flex-shrink",
                    "flex-basis",
                    "flex-direction",
                    "flex-flow",
                    "flex-wrap",
                    "order",
                    "grid",
                    "grid-area",
                    "grid-template",
                    "grid-template-areas",
                    "grid-template-columns",
                    "grid-template-rows",
                    "grid-auto-columns",
                    "grid-auto-rows",
                    "grid-auto-flow",
                    "grid-column",
                    "grid-column-start",
                    "grid-column-end",
                    "grid-row",
                    "grid-row-start",
                    "grid-row-end",
                    "visibility",
                    "backface-visibility",
                    "opacity",
                    "break-after",
                    "break-before",
                    "break-inside",
                    "place-content",
                    "place-items",
                    "place-self",
                    "writing-mode",
                    "contain"
                ]
            },
            {
                groupName: "dimensions",
                emptyLineBefore: "always",
                unspecified: "ignore",
                emptyLineMinimumPropertyThreshold: 0,
                properties: [
                    "box-sizing",
                    "overflow",
                    "overflow-x",
                    "overflow-y",
                    "overflow-wrap",
                    "width",
                    "min-width",
                    "max-width",
                    "height",
                    "min-height",
                    "max-height",
                    "min-block-size",
                    "min-inline-size",
                    "max-block-size",
                    "max-inline-size",
                    "flex",
                    "padding",
                    "padding-top",
                    "padding-right",
                    "padding-bottom",
                    "padding-left",
                    "padding-block-start",
                    "padding-block-end",
                    "padding-inline-start",
                    "padding-inline-end",
                    "border",
                    "border-top",
                    "border-right",
                    "border-bottom",
                    "border-left",
                    "border-width",
                    "border-top-width",
                    "border-right-width",
                    "border-bottom-width",
                    "border-left-width",
                    "border-block-start",
                    "border-block-start-width",
                    "border-block-end",
                    "border-block-end-width",
                    "border-inline-start",
                    "border-inline-start-color",
                    "border-inline-start-style",
                    "border-inline-start-width",
                    "border-inline-end",
                    "border-inline-end-color",
                    "border-inline-end-style",
                    "border-inline-end-width",
                    "margin",
                    "margin-top",
                    "margin-right",
                    "margin-bottom",
                    "margin-left",
                    "margin-block-start",
                    "margin-block-end",
                    "margin-inline-start",
                    "margin-inline-end",
                    "block-size",
                    "inline-size",
                    "gap",
                    "columns",
                    "column-count",
                    "column-fill",
                    "column-gap",
                    "column-rule",
                    "column-rule-color",
                    "column-rule-style",
                    "column-rule-width",
                    "column-span",
                    "column-width",
                    "row-gap",
                    "clip",
                    "clip-path",
                    "clip-rule",
                    "transform",
                    "transform-box",
                    "transform-style",
                    "transform-origin",
                    "zoom",
                    "aspect-ratio"
                ]
            },
            {
                groupName: "visual",
                emptyLineBefore: "always",
                unspecified: "ignore",
                emptyLineMinimumPropertyThreshold: 0,
                properties: [
                    "appearance",
                    "background",
                    "background-color",
                    "background-image",
                    "background-repeat",
                    "background-attachment",
                    "background-position",
                    "background-position-x",
                    "background-position-y",
                    "background-blend-mode",
                    "background-clip",
                    "background-origin",
                    "background-size",
                    "filter",
                    "backdrop-filter",
                    "color",
                    "outline",
                    "outline-width",
                    "outline-style",
                    "outline-color",
                    "outline-offset",
                    "list-style",
                    "list-style-position",
                    "list-style-type",
                    "list-style-image",
                    "border-style",
                    "border-top-style",
                    "border-right-style",
                    "border-bottom-style",
                    "border-left-style",
                    "border-radius",
                    "border-top-left-radius",
                    "border-top-right-radius",
                    "border-bottom-right-radius",
                    "border-bottom-left-radius",
                    "border-start-start-radius",
                    "border-start-end-radius",
                    "border-end-end-radius",
                    "border-end-start-radius",
                    "border-color",
                    "border-top-color",
                    "border-right-color",
                    "border-bottom-color",
                    "border-left-color",
                    "border-block-end-color",
                    "border-block-end-style",
                    "border-block-start-color",
                    "border-block-start-style",
                    "box-shadow",
                    "mask",
                    "mask-clip",
                    "mask-composite",
                    "mask-image",
                    "mask-mode",
                    "mask-origin",
                    "mask-position",
                    "mask-repeat",
                    "mask-size",
                    "shape-image-threshold",
                    "shape-margin",
                    "shape-outside",
                    "shape-rendering",
                    "mix-blend-mode",
                    "object-fit",
                    "object-position",
                    "border-image",
                    "border-image-outset",
                    "border-image-repeat",
                    "border-image-slice",
                    "border-image-source",
                    "border-image-width",
                    "perspective",
                    "perspective-origin",
                    "scrollbar-width",
                    "scrollbar-color"
                ]
            },
            {
                groupName: "text",
                emptyLineBefore: "always",
                unspecified: "ignore",
                emptyLineMinimumPropertyThreshold: 0,
                properties: [
                    "font",
                    "font-display",
                    "font-family",
                    "font-size",
                    "font-style",
                    "font-weight",
                    "font-variant",
                    "font-variant-alternates",
                    "font-variant-caps",
                    "font-variant-emoji",
                    "font-variant-ligatures",
                    "font-variant-numeric",
                    "font-variant-position",
                    "font-size-adjust",
                    "font-stretch",
                    "font-effect",
                    "font-emphasize",
                    "font-emphasize-position",
                    "font-emphasize-style",
                    "font-smoothing",
                    "font-feature-settings",
                    "hyphens",
                    "line-break",
                    "line-height",
                    "text-align",
                    "text-align-last",
                    "text-emphasis",
                    "text-emphasis-color",
                    "text-emphasis-style",
                    "text-emphasis-position",
                    "text-decoration",
                    "text-decoration-color",
                    "text-decoration-line",
                    "text-decoration-style",
                    "text-decoration-skip",
                    "text-decoration-skip-ink",
                    "text-decoration-thickness",
                    "text-underline-offset",
                    "text-indent",
                    "text-justify",
                    "text-outline",
                    "text-overflow",
                    "text-overflow-ellipsis",
                    "text-overflow-mode",
                    "text-shadow",
                    "text-transform",
                    "text-wrap",
                    "letter-spacing",
                    "word-spacing",
                    "letter-spacing",
                    "text-rendering",
                    "word-break",
                    "word-spacing",
                    "word-wrap",
                    "white-space",
                    "caret-color",
                    "caret-shape",
                    "tab-size",
                    "text-overflow",
                    "vertical-align",
                    "unicode-bidi",
                    "direction",
                    "text-box-trim",
                    "text-box-edge"
                ]
            },
            {
                groupName: "table",
                emptyLineBefore: "always",
                unspecified: "ignore",
                emptyLineMinimumPropertyThreshold: 0,
                properties: ["table-layout", "border-collapse", "border-spacing", "empty-cells", "caption-side"]
            },
            {
                groupName: "svg",
                emptyLineBefore: "always",
                unspecified: "ignore",
                emptyLineMinimumPropertyThreshold: 0,
                properties: [
                    "x",
                    "y",
                    "cx",
                    "cy",
                    "r",
                    "rx",
                    "ry",
                    "vector-effect",
                    "paint-order",
                    "fill",
                    "fill-opacity",
                    "fill-rule",
                    "stroke",
                    "stroke-opacity",
                    "stroke-width",
                    "stroke-dasharray",
                    "stroke-dashoffset",
                    "stroke-linecap",
                    "stroke-linejoin",
                    "stroke-miterlimit",
                    "stop-color",
                    "stop-opacity",
                    "marker",
                    "marker-end",
                    "marker-mid",
                    "marker-start",
                    "flood-color",
                    "flood-opacity",
                    "shape-rendering",
                    "color-interpolation",
                    "color-interpolation-filters",
                    "lighting-color",
                    "text-anchor",
                    "dominant-baseline"
                ]
            },
            {
                groupName: "meta",
                emptyLineBefore: "always",
                unspecified: "ignore",
                emptyLineMinimumPropertyThreshold: 0,
                properties: [
                    "src",
                    "content",
                    "quotes",
                    "counter-reset",
                    "counter-increment",
                    "syntax",
                    "inherits",
                    "initial-value"
                ]
            },
            {
                groupName: "interaction",
                emptyLineBefore: "always",
                unspecified: "ignore",
                emptyLineMinimumPropertyThreshold: 0,
                properties: [
                    "cursor",
                    "user-select",
                    "pointer-events",
                    "touch-action",
                    "resize",
                    "anchor-name",
                    "position-anchor",
                    "position-area",
                    "position-try-fallbacks",
                    "position-try-order",
                    "position-try",
                    "position-visibility"
                ]
            },
            {
                groupName: "animation",
                emptyLineBefore: "always",
                unspecified: "ignore",
                emptyLineMinimumPropertyThreshold: 0,
                properties: [
                    "animation",
                    "animation-name",
                    "animation-duration",
                    "animation-timing-function",
                    "animation-delay",
                    "animation-iteration-count",
                    "animation-direction",
                    "animation-fill-mode",
                    "animation-play-state",
                    "transition",
                    "transition-behavior",
                    "transition-delay",
                    "transition-timing-function",
                    "transition-duration",
                    "transition-property",
                    "scroll-behavior",
                    "scrollbar-gutter",
                    "overscroll-behavior",
                    "scroll-snap-type",
                    "scroll-snap-align",
                    "will-change",
                    "interpolate-size"
                ]
            }
        ]
    }
};
